name: Optimize hero image

on:
  push:
    paths:
      - 'InksLakeSunset.jpg'
      - '.github/workflows/optimize-hero-image.yml'
  workflow_dispatch: {}

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cwebp and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y webp imagemagick

      - name: Convert JPG to WebP
        run: |
          if [ -f InksLakeSunset.jpg ]; then
            cwebp -q 80 InksLakeSunset.jpg -o InksLakeSunset.webp
          fi

      - name: Compress JPG (strip metadata and set quality)
        run: |
          if [ -f InksLakeSunset.jpg ]; then
            # Create a temp copy to avoid in-place unexpected behavior
            cp InksLakeSunset.jpg InksLakeSunset.tmp.jpg
            magick InksLakeSunset.tmp.jpg -strip -interlace Plane -sampling-factor 4:2:0 -quality 80 InksLakeSunset.jpg
            rm -f InksLakeSunset.tmp.jpg
          fi

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add InksLakeSunset.webp InksLakeSunset.jpg || true
            git commit -m "chore: optimize hero image (webp + jpg)"
            git push
          fi
