name: Update README with Latest Blog Posts

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet

    - name: Fetch Latest Blog Posts
      id: fetch_blog_posts
      run: |
        # Fetch the latest blog posts from the RSS feed
        curl -s https://markhazleton.com/rss.xml | xmlstarlet sel -t -m '//item' \
        -v 'concat("- [", title, "](", link, ")")' -n | head -5 > latest-posts.md

    - name: Update README.md
      run: |
        # Read the latest posts into a variable
        latest_posts=$(<latest-posts.md)

        # Replace the placeholder text between the <!-- BLOG-POST-LIST:START --> and <!-- BLOG-POST-LIST:END --> tags
        # Ensure only one set of latest posts is present
        awk -v latest_posts="$latest_posts" '
        BEGIN {print_part=1}
        /<!-- BLOG-POST-LIST:START -->/ {print_part=1; print; print latest_posts; next}
        /<!-- BLOG-POST-LIST:END -->/ {print_part=0; print; next}
        print_part {print}
        ' README.md > updated_readme.md

    - name: Check if README.md was updated
      run: |
        # Compare updated README.md with the current one
        if ! diff updated_readme.md README.md > /dev/null; then
          mv updated_readme.md README.md
        else
          echo "README.md is up to date. No changes needed."
          exit 0
        fi

    - name: Commit Changes
      if: success() && steps.update-readme.outputs.changed == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Updated README with latest blog posts"
        git push
